################################################################################

# This Makefile generated by GoMakeGen 0.8.0 using next command:
# gomakegen --metalinter --strip .

################################################################################

.DEFAULT_GOAL := help
.PHONY = fmt all clean deps metalinter help

################################################################################

all: source-index ## Build all binaries

source-index: ## Build source-index binary
	go build -ldflags="-s -w" source-index.go

install: ## Install binaries
	cp source-index /usr/bin/source-index

uninstall: ## Uninstall binaries
	rm -f /usr/bin/source-index

deps: ## Download dependencies
	git config --global http.https://pkg.re.followRedirects true
	go get -d -v pkg.re/essentialkaos/ek.v9

fmt: ## Format source code with gofmt
	find . -name "*.go" -exec gofmt -s -w {} \;

metalinter: ## Install and run gometalinter
	test -s $(GOPATH)/bin/gometalinter || (go get -u github.com/alecthomas/gometalinter ; $(GOPATH)/bin/gometalinter --install)
	$(GOPATH)/bin/gometalinter --deadline 30s

clean: ## Remove generated files
	rm -f source-index

help: ## Show this info
	@echo -e '\nSupported targets:\n'
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[33m%-12s\033[0m %s\n", $$1, $$2}'
	@echo -e ''

################################################################################
